export const inputs = [
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "test1", "type": "test"}, 
    {"name": "test31", "type":"defaultType"},
    {"name": "test32", "type": "testing"},
    {"name": "test33", "type": "testing"},
    {"name": "newt", "type": "newt"}
  ];
  